ControleWeb2/Models/Equipamentos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleWeb2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipamentos()
        {
            this.Transacoes = new HashSet<Transacoes>();
        }
    
        public int Id { get; set; }
        public string Equipamento { get; set; }
        public string Modelo { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string Local { get; set; }
        public string Armario { get; set; }
        public Nullable<int> Prateleira { get; set; }
        public string SistOper { get; set; }
        public string AplicativoInstalado { get; set; }
        public string SistemaAutomação { get; set; }
        public string Status { get; set; }
        public string PC { get; set; }
        public string RC { get; set; }
        public string ItemRC { get; set; }
        public string NF { get; set; }
        public Nullable<System.DateTime> DataGarantia { get; set; }
        public string Observacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacoes> Transacoes { get; set; }
    }
}

ControleWeb2/Controllers/EquipamentosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ControleWeb2.Models;
using PagedList;

namespace ControleWeb2.Controllers
{
    public class EquipamentosController : Controller
    {
        private ControleWebEntities db = new ControleWebEntities();

        // GET: Equipamentos
        /*public async Task<ActionResult> Index()
        {
            return View(await db.Equipamentos.ToListAsync());
        }*/
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.EquipamentosSortParm = String.IsNullOrEmpty(sortOrder) ? "equipamentos_desc" : "";
            ViewBag.SerialNumberSortParm = String.IsNullOrEmpty(sortOrder) ? "serialnumber_asc" : "serialnumber_desc";
            ViewBag.SistemaAutomacaoSortParm = String.IsNullOrEmpty(sortOrder) ? "sistemaautomacao_asc" : "";
            //ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var equipamentos = from s in db.Equipamentos
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                equipamentos = equipamentos.Where(s => s.Equipamento.Contains(searchString)
                                                || s.Modelo.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "equipamentos_desc":
                    equipamentos = equipamentos.OrderByDescending(s => s.Equipamento);
                    break;
                case "serialnumber_asc":
                    equipamentos = equipamentos.OrderBy(s => s.SerialNumber);
                    break;
                case "serialnumber_desc":
                    equipamentos = equipamentos.OrderByDescending(s => s.SerialNumber);
                    break;
                case "sistemaautomacao_asc":
                    equipamentos = equipamentos.OrderBy(s => s.SistemaAutomação);
                    break;
                default:
                    equipamentos = equipamentos.OrderBy(s => s.Equipamento);
                    break;
            }

            int pageSize = 50;
            int pageNumber = (page ?? 1);
            return View(equipamentos.ToPagedList(pageNumber, pageSize));

            //return View(equipamentos.ToList());
        }

        // GET: Equipamentos/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipamentos equipamentos = await db.Equipamentos.FindAsync(id);
            if (equipamentos == null)
            {
                return HttpNotFound();
            }
            return View(equipamentos);
        }

        // GET: Equipamentos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Equipamentos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Equipamento,Modelo,SerialNumber,DataCadastro,Local,Armario,Prateleira,SistOper,AplicativoInstalado,SistemaAutomação,Status,PC,RC,ItemRC,NF,DataGarantia,Observacao")] Equipamentos equipamentos)
        {
            if (ModelState.IsValid)
            {
                db.Equipamentos.Add(equipamentos);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(equipamentos);
        }

        // GET: Equipamentos/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipamentos equipamentos = await db.Equipamentos.FindAsync(id);
            if (equipamentos == null)
            {
                return HttpNotFound();
            }
            return View(equipamentos);
        }

        // POST: Equipamentos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Equipamento,Modelo,SerialNumber,DataCadastro,Local,Armario,Prateleira,SistOper,AplicativoInstalado,SistemaAutomação,Status,PC,RC,ItemRC,NF,DataGarantia,Observacao")] Equipamentos equipamentos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(equipamentos).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(equipamentos);
        }

        // GET: Equipamentos/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipamentos equipamentos = await db.Equipamentos.FindAsync(id);
            if (equipamentos == null)
            {
                return HttpNotFound();
            }
            return View(equipamentos);
        }

        // POST: Equipamentos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Equipamentos equipamentos = await db.Equipamentos.FindAsync(id);
            db.Equipamentos.Remove(equipamentos);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ControleWeb2/Views/Equipamentos/Create.cshtml
@model ControleWeb2.Models.Equipamentos

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Equipamentos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Equipamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Equipamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Equipamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataCadastro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataCadastro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataCadastro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Local, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Local, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Local, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Armario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Armario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Armario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prateleira, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prateleira, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prateleira, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SistOper, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SistOper, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SistOper, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AplicativoInstalado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AplicativoInstalado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AplicativoInstalado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SistemaAutomação, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SistemaAutomação, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SistemaAutomação, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemRC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemRC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemRC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataGarantia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataGarantia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataGarantia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ControleWeb2/Views/Equipamentos/Delete.cshtml
@model ControleWeb2.Models.Equipamentos

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Equipamentos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Equipamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Equipamento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Local)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Local)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Armario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Armario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prateleira)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prateleira)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SistOper)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SistOper)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AplicativoInstalado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AplicativoInstalado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SistemaAutomação)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SistemaAutomação)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemRC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemRC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataGarantia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataGarantia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ControleWeb2/Views/Equipamentos/Details.cshtml
@model ControleWeb2.Models.Equipamentos

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Equipamentos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Equipamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Equipamento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Local)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Local)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Armario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Armario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prateleira)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prateleira)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SistOper)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SistOper)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AplicativoInstalado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AplicativoInstalado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SistemaAutomação)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SistemaAutomação)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemRC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemRC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataGarantia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataGarantia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ControleWeb2/Views/Equipamentos/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<ControleWeb2.Models.Equipamentos>
<!--IEnumerable<ControleWeb2.Models.Equipamentos> -->
@{
    ViewBag.Title = "Index";
}

<h2>Equipamentos</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Equipamentos", FormMethod.Get))
{
    <p>
        Procurar por Equipamento: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Pesquisar" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Equipamento", "Index", new { sortOrder = ViewBag.EquipamentosSortParm, currentFilter = ViewBag.CurrentFilter })
            <!-- @Html.ActionLink("Equipamento", "Index", new { sortOrder = ViewBag.EquipamentosSortParm }) Ordenação-->

        </th>
        <th>
            Modelo

        </th>
        <th>
            @Html.ActionLink("SerialNumber", "Index", new { sortOrder = ViewBag.SerialNumberSortParm, currentFilter = ViewBag.CurrentFilter })
            <!-- @Html.ActionLink("SerialNumber", "Index", new { sortOrder = ViewBag.SerialNumberSortParm }) Ordenação -->

        </th>
        <!--<th>
             Data Cadastro
        </th> -->
        <th>
            Local
        </th>
        <th>
            Armario
        </th>
        <th>
            Prateleira
        </th>
        <!--<th>
            Sistema Operacional
        </th>
        <th>
            Aplicativo Instalado
        </th> -->
        <th>
            @Html.ActionLink("SistemaAutomacao", "Index", new { sortOrder = ViewBag.SistemaAutomacaoSortParm, currentFilter = ViewBag.CurrentFilter })
            <!-- @Html.ActionLink("SistemaAutomacao", "Index", new { sortOrder = ViewBag.SistemaAutomacaoSortParm }) -->

        </th>
        <!--<th>
            Status
        </th>
        <th>
            PC
        </th>
        <th>
            RC
        </th>
        <th>
            Item RC
        </th>
        <th>
            NF
        </th>
        <th>
            Data de Garantia
        </th> -->
        <th>
            Observação
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Equipamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <!--<td>
                @Html.DisplayFor(modelItem => item.DataCadastro)
            </td> -->
            <td>
                @Html.DisplayFor(modelItem => item.Local)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Armario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prateleira)
            </td>
            <!--<td>
                @Html.DisplayFor(modelItem => item.SistOper)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AplicativoInstalado)
            </td> -->
            <td>
                @Html.DisplayFor(modelItem => item.SistemaAutomação)
            </td>
            <!--<td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ItemRC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataGarantia)
            </td> -->
            <td>
                @Html.DisplayFor(modelItem => item.Observacao)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))